name: Run PHPUnit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
